language: bash
services: docker

matrix:
  include:
    - env: REPO=master TAG=master
    - env: REPO=1908 TAG=19.08
    - env: REPO=1904 TAG=19.04
    - env: REPO=release TAG=latest

before_script:
  - env | sort
  - export DOCKER_REPO="ligato/vpp-base"

script:
  - |
    (
      set -Eexuo pipefail
      make build
      image="${DOCKER_REPO}:${TAG}"
      docker run --rm "$image" dpkg-query -f '${Version}' -W vpp
    )

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: make push
  on:
    branch: master

notifications:
  slack:
    rooms:
      - ligato:QNOK2VgHH6k40T8nQxmSgRmo
    on_success: change
    on_failure: always
